# Kubernetes API verziója
apiVersion: v1
# Objektum típusa
kind: ConfigMap
# Metadata a ConfigMap azonosításához
metadata:
  name: devops-config
  labels:
    app: devops-app
# Adatok tárolása (környezeti változókhoz használva)
data:
  # A ConfigMap-ben tárolt környezeti változó (VERSION_INFO)
  VERSION_INFO: "v1.0-ConfigMap-Loaded"
  # A konténer portja, ami megegyezik a Dockerfile-ban és app.py-ban definiálttal
  APP_PORT: "8080"